### PR TITLE
Bot can join multiple servers

### PR DESCRIPTION
**Pull request by FQS-0**
The Discord bot can join multiple servers. Battle reports parsed by the /kb command will only be sent to the server from which the command originated. Battle reports from the News Agency will be shared with every server (untested).

### CODE REVIEW

**Comment by degola** [comment]
Thanks @FQS-0, i'm not exactly sure how multi guilds/discord servers work with Discord.js, I'm assuming that you would add the bot for now manually by running the url https://discord.com/api/oauth2/authorize?client_id=&permissions=&scope=bot with the corresponding ids? The bots client id / application id is 1113485760604147784 and the required permissions are 2147560450 (i added a few permissions due to that i want to add a feature which also mentions usernames if they are found on the corresponding discord server either as attacker or defender).

I'm going to deploy it on my server and you can test it if you want to.

**Comment by FQS-0** [comment]
> I'm assuming that you would add the bot for now manually by running the url https://discord.com/api/oauth2/authorize?client_id=&permissions=&scope=bot with the corresponding ids? 

Yes, that's how it works. But right now only you can add the bot to a server, because your bot is private. In the Discord developer portal under _Settings - Bot_ you can make the bot public: 

> PUBLIC BOT
> Public bots can be added by anyone. When unchecked, only you can join this bot to servers.

**Comment by degola** [comment]
@FQS-0 thanks, i just made the bot publicly available.

**Comment by FQS-0** [comment]
It works.

**Pull request merged**
